CREATE TABLE customer (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER,
    LAST_NAME VARCHAR2(100),
    SALARY NUMBER
);

INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (1, 'Carlos', 32, 'Mamani', 2000.00);
INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (2, 'Juan', 25, 'Zuñiga', 1500.00);
INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (3, 'Sara', 23, 'Saavedra', 2000.00);
INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (4, 'Eva', 25, 'Perez', 6500.00);
INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (5, 'Luis', 27, 'Poma', 8500.00);
INSERT INTO customer (ID, NAME, AGE, LAST_NAME, SALARY) VALUES (6, 'Jose', 22, 'Quispe', 4500.00);

COMMIT;